spring:
  application:
    name: ema
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ema}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true